package fr.eseo.e3a.myminifarm.model.json;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * The TilesetJson class represents a tileset in the map.
 * It a part of the json data generated by Tiled, a map editor.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class TilesetJson {
    private int firstgid;

    /**
     * Used to get the firstgid of the tileset.
     *
     * @return The firstgid of the tileset.
     */
    public int getFirstgid() {
        return firstgid;
    }

    /**
     * Used to set the firstgid of the tileset.
     *
     * @param firstgid The firstgid to set.
     */
    public void setFirstgid(int firstgid) {
        this.firstgid = firstgid;
    }

    /**
     * This method is used to convert the tileset data to a string representation.
     *
     * @return A string representation of the tileset data.
     */
    public String toString() {
        return "TilesetJson{\n" +
                "firstgid=" + firstgid + "\n" +
                '}';
    }
}
