package fr.eseo.e3a.myminifarm.model;

import com.fasterxml.jackson.databind.ObjectMapper;
import fr.eseo.e3a.myminifarm.controller.GameLoop;
import fr.eseo.e3a.myminifarm.model.farmElement.*;
import fr.eseo.e3a.myminifarm.controller.GameLoop;
import fr.eseo.e3a.myminifarm.model.farmElement.CropCell;
import fr.eseo.e3a.myminifarm.model.farmElement.FarmEnums;
import fr.eseo.e3a.myminifarm.model.farmElement.Machine;
import fr.eseo.e3a.myminifarm.model.json.LayerJson;
import fr.eseo.e3a.myminifarm.model.json.MapJson;
import fr.eseo.e3a.myminifarm.utils.Movements;
import fr.eseo.e3a.myminifarm.utils.Point2D;
import fr.eseo.e3a.myminifarm.utils.Vector2;

import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.HashMap;
import java.util.List;
import java.util.stream.Collectors;

/**
 * The Map class represents is a model of the game map.
 * It contains the map data and provides methods to manipulate and access the map.
 */
public class Map {
    private static final float radius = 1f;

    private MapJson mapJson;

    private LayerJson collisionLayer;

    private HashMap<Vector2, Item> dropedItem = new HashMap<>();
    private HashMap<Point2D, Machine> machines = new HashMap<>();
    private HashMap<Point2D, Container> containers = new HashMap<>();
    private HashMap<Point2D, CropCell> cropCells = new HashMap<>();

    private boolean machineHasChange = true;
    private boolean containerHasChanged = true;
    private boolean cropCellHasChange = true;
    private boolean plantCropHasChange = true;
    private boolean dropItemHasChange = true;

    private Vector2 pos;

    /**
     * Constructor for the Map class.
     * It initializes the map using a JSON file.
     * The JSON is generated by Tiled, a map editor.
     *
     * @param jsonPath The path to the JSON file containing the map data.
     */
    public Map(String jsonPath) {
        ObjectMapper objectMapper = new ObjectMapper();
        try {
            mapJson = objectMapper.readValue(new File(jsonPath), MapJson.class);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        for (LayerJson layer : mapJson.getLayers()) {
            if (layer.getName().equals("collider")) {
                collisionLayer = layer;
            }
        }
    }

    /**
     * Get the map data in Object form.
     *
     * @return The map data as a MapJson object.
     */
    public MapJson getMapJson() {
        return mapJson;
    }

    /**
     * This method is used to convert the map data to a string representation.
     *
     * @return A string representation of the map data.
     */
    public String toString() {
        return "Map{" +
                "mapJson=" + mapJson +
                '}';
    }

    public Vector2 getPos() {
        return pos;
    }

    public void setPos(Vector2 pos) {
        this.pos = new Vector2(pos.x(), pos.y());
    }

    /**
     * This method is used to check if a given position is valid on the map.
     * X is used to get the orientation of the player.
     *
     * @param pos     The position to check.
     * @param orientX The X orientation of the player.
     * @return true if the position is valid, false otherwise.
     */
    public boolean isValidPosX(Vector2 pos, int orientX) {
        // Check if the position is within the bounds of the map
        if (orientX < 0 && pos.x() <= 0) {
            return false;
        }
        if (orientX > 0 && pos.x() >= mapJson.getWidth()) {
            return false;
        }
        if (isCollision(Movements.cellPos(pos))) {
            return false;
        }
        return true;
    }

    /**
     * This method is used to check if a given position is valid on the map.
     * Y is used to get the orientation of the player.
     *
     * @param pos     The position to check.
     * @param orientY The Y orientation of the player.
     * @return true if the position is valid, false otherwise.
     */
    public boolean isValidPosY(Vector2 pos, int orientY) {
        if (orientY < 0 && pos.y() <= 0) {
            return false;
        }
        if (orientY > 0 && pos.y() >= mapJson.getHeight()) {
            return false;
        }
        if (isCollision(Movements.cellPos(pos))) {
            return false;
        }
        return true;
    }

    public boolean isCollision(Point2D pos) {

        // Check if the position is within the bounds of the map
        if (pos.x() < 0 || pos.x() >= mapJson.getWidth()) {
            return false;
        }
        if (pos.y() < 0 || pos.y() >= mapJson.getHeight()) {
            return false;
        }
        // Check if the tile at the position is solid
        int tileId = collisionLayer.getData().get((int) pos.y() * mapJson.getWidth() + (int) pos.x());
        return tileId != 0;
    }

    public void addCollision(Point2D pos, int width, int height) {
        for (int i = 0; i < width; i++) {
            for (int j = 0; j < height; j++) {
                collisionLayer.getData().set(((int) pos.y() + j) * mapJson.getWidth() + ((int) pos.x() + i), 1);
            }
        }
    }

    public void removeCollision(Point2D pos, int width, int height) {
        for (int i = 0; i < width; i++) {
            for (int j = 0; j < height; j++) {
                collisionLayer.getData().set(((int) pos.y() + j) * mapJson.getWidth() + ((int) pos.x() + i), 0);
            }
        }
    }

    public boolean isCellOccupiedByMachine(Point2D pos) {
        return machines.containsKey(pos);
    }

    public boolean isCellOccupiedByContainer(Point2D pos) {
        return containers.containsKey(pos);
    }

    public boolean isCellOccupiedByCropCell(Point2D pos) {
        return cropCells.containsKey(pos);
    }

    public boolean isCellOccupied(Point2D pos) {
        return isCellOccupiedByMachine(pos) || isCellOccupiedByCropCell(pos) || isCellOccupiedByContainer(pos);
    }

    public boolean addMachine(Point2D pos, Machine machine) {
        if (isCellOccupied(pos) || isCollision(pos)) {
            return false;
        }

        Point2D newPos = new Point2D(pos.x(), pos.y() - 1);

        machines.put(pos, machine);
        addCollision(newPos, 1, 2);
        machineHasChange = true;

        return true;
    }

    public boolean removeMachine(Point2D pos) {
        if (!machines.containsKey(pos)) {
            return false;
        }

        Point2D newPos = new Point2D(pos.x(), pos.y() - 1);

        machines.remove(pos);
        removeCollision(newPos, 1, 2);
        machineHasChange = true;

        return true;
    }

    public Machine getMachine(Point2D pos) {
        return machines.get(pos);
    }

    public HashMap<Point2D, Machine> getMachines() {
        return machines;
    }

    public boolean addContainer(Point2D pos, Container container) {
        if (isCellOccupied(pos) || isCollision(pos)) {
            return false;
        }

        Point2D newPos = new Point2D(pos.x(), pos.y() - 1);

        containers.put(pos, container);
        addCollision(newPos, 1, 2);
        containerHasChanged = true;

        return true;
    }

    public boolean removeContainer(Point2D pos) {
        if (!containers.containsKey(pos)) {
            return false;
        }

        Point2D newPos = new Point2D(pos.x(), pos.y() - 1);

        containers.remove(pos);
        removeCollision(newPos, 1, 2);
        containerHasChanged = true;

        return true;
    }

    public Container getContainer(Point2D pos) {
        return containers.get(pos);
    }

    public HashMap<Point2D, Container> getContainers() {
        return containers;
    }

    public boolean addCropCell(Point2D pos) {
        if (isCellOccupied(pos) || isCollision(pos)) {
            return false;
        }

        cropCells.put(pos, new CropCell());
        cropCellHasChange = true;

        return true;
    }

    public boolean removeCropCell(Point2D pos) {
        if (!cropCells.containsKey(pos)) {
            return false;
        }

        cropCells.remove(pos);
        cropCellHasChange = true;

        return true;
    }

    public CropCell getCropCell(Point2D pos) {
        return cropCells.get(pos);
    }

    public HashMap<Point2D, CropCell> getCropCells() {
        return cropCells;
    }


    public Object removeElement(Point2D pos) {
        if (machines.containsKey(pos)) {
            Machine machine = machines.get(pos);
            removeMachine(pos);
            if (machine.getInventory().containItem()) {
                for (int i = 0; i < machine.getInventory().getSize(); i++) {
                    if (machine.getInventory().getItem(i) != null) {
                        GameLoop.getInstance().getPlayer().tryAddItemInventory(machine.getInventory().getItem(i), new Vector2(pos.x(), pos.y()));
                        machine.getInventory().remove(i);
                    }
                }
            }
            machineHasChange = true;
            return machine;
        } else if (containers.containsKey(pos)) {
            Container container = containers.get(pos);
            removeContainer(pos);
            if (container.getInventory().containItem()) {
                for (int i = 0; i < container.getInventory().getSize(); i++) {
                    if (container.getInventory().getItem(i) != null) {
                        GameLoop.getInstance().getPlayer().tryAddItemInventory(container.getInventory().getItem(i), new Vector2(pos.x(), pos.y()));
                        container.getInventory().remove(i);
                    }
                }
            }
            containerHasChanged = true;
            return container;

        } else if (cropCells.containsKey(pos)) {
            removeCropCell(pos);
            cropCellHasChange = true;
        }
        return null;
    }

    public HashMap<Vector2, Item> getDropedItem() {
        return dropedItem;
    }

    public void dropItem(Vector2 pos, Item item) {
        Vector2 randomPos = new Vector2(pos.x() + (float) Math.random() * radius, pos.y() + (float) Math.random() * radius);
        dropedItem.put(randomPos, item);
        dropItemHasChange = true;
    }

    public void dropItem(Point2D pos, Item item) {
        Vector2 newPos = new Vector2(pos.x(), pos.y());
        dropItem(newPos, item);
    }

    public void getDropItem(Vector2 pos) {
        Vector2 topLeft = new Vector2(pos.x() - radius, pos.y() - radius);
        Vector2 bottomRight = new Vector2(pos.x() + radius, pos.y() + radius);

        HashMap<Vector2, Item> itemsInArea = getItemsInArea(dropedItem, topLeft, bottomRight);

        for (HashMap.Entry<Vector2, Item> entry : itemsInArea.entrySet()) {
            Vector2 position = entry.getKey();
            Item item = entry.getValue();

            boolean isAdded = GameLoop.getInstance().getPlayer().getInventory().add(item);
            if (isAdded) {
                dropedItem.remove(position);
                dropItemHasChange = true;
            }
        }
    }

    private HashMap<Vector2, Item> getItemsInArea(HashMap<Vector2, Item> map, Vector2 min, Vector2 max) {
        return map.entrySet().stream()
                .filter(entry -> {
                    Vector2 pos = entry.getKey();
                    return pos.x() >= min.x() && pos.x() <= max.x() &&
                            pos.y() >= min.y() && pos.y() <= max.y();
                })
                .collect(Collectors.toMap(
                        HashMap.Entry::getKey,
                        HashMap.Entry::getValue,
                        (e1, e2) -> e1,
                        HashMap::new
                ));
    }

    public boolean isInPerimeter(Vector2 center, Vector2 pos) {
        Vector2 min = new Vector2(center.x() - radius * 2, center.y() - radius * 2);
        Vector2 max = new Vector2(center.x() + radius * 2, center.y() + radius * 2);
        return pos.x() >= min.x() && pos.x() <= max.x() &&
                pos.y() >= min.y() && pos.y() <= max.y();
    }


    public boolean hasMachineChange() {
        return machineHasChange;
    }

    public void setMachineChange(boolean hasChanged) {
        this.machineHasChange = hasChanged;
    }

    public boolean hasContainerChange() {
        return containerHasChanged;
    }

    public void setContainerChange(boolean hasChanged) {
        this.containerHasChanged = hasChanged;
    }

    public boolean hasCropCellChange() {
        return cropCellHasChange;
    }

    public void setCropCellChange(boolean hasChanged) {
        this.cropCellHasChange = hasChanged;
    }

    public boolean hasPlantCropChange() {
        return plantCropHasChange;
    }

    public void setPlantCropChange(boolean hasChanged) {
        this.plantCropHasChange = hasChanged;
    }

    public boolean hasDropItemChange() {
        return dropItemHasChange;
    }

    public void setDropItemChange(boolean hasChanged) {
        this.dropItemHasChange = hasChanged;
    }

    public LayerJson getCollisionLayer() {
        return collisionLayer;
    }
}
